import GameofInequality as main
class Cards:
    go = main.Card(main.CardType.GO, "GO", 1)
    okr = main.Card(main.CardType.PROPERTY, "Old Kent Road", 2, b=60, c=main.Set.BROWN)
    chest1 = main.Card(main.CardType.COMMUNITYCHEST, "Community Chest Card", 3)
    wchr = main.Card(main.CardType.PROPERTY, "Whitechapel Road", 4, b=60, c=main.Set.BROWN)
    itax = main.Card(main.CardType.TAX, "Income Tax", 5, b=200)
    kcs = main.Card(main.CardType.RAILROAD, "King's Cross Station", 6)
    tai = main.Card(main.CardType.PROPERTY, "The Angel, Islington", 7, b=100, c=main.Set.CYAN)
    chance1 = main.Card(main.CardType.CHANCE, "Chance Card", 8)
    er = main.Card(main.CardType.PROPERTY, "Euston Road", 9, b=100, c=main.Set.CYAN)
    pvr = main.Card(main.CardType.PROPERTY, "Pentonville Road", 10, b=120, c=main.Set.BROWN)
    jail = main.Card(main.CardType.FREE, "Just Visiting/Jail", 11)
    pm = main.Card(main.CardType.PROPERTY, "Pall Mall", 12, b=140, c=main.Set.PURPLE)
    ecomp = main.Card(main.CardType.UTILITY, "Electric Company", 13)
    wh = main.Card(main.CardType.PROPERTY, "Whitehall", 14, b=140, c=main.Set.PURPLE)
    nta = main.Card(main.CardType.PROPERTY, "Northumb'nd Avenue", 15, b=160, c=main.Set.PURPLE)
    mbs = main.Card(main.CardType.RAILROAD, "Marylebone Station", 16)
    bs = main.Card(main.CardType.PROPERTY, "Bow Street", 17, b=180, c=main.Set.ORANGE)
    chest2 = main.Card(main.CardType.COMMUNITYCHEST, "Community Chest Card", 18)
    gms = main.Card(main.CardType.PROPERTY, "Great Marlborough Street", 19, b=180, c=main.Set.ORANGE)
    vs = main.Card(main.CardType.PROPERTY, "Vine Street", 20, b=200, c=main.Set.ORANGE)
    fp = main.Card(main.CardType.FREE, "Free Parking", 21)
    str = main.Card(main.CardType.PROPERTY, "Strand", 22, b=220, c=main.Set.RED)
    chance2 = main.Card(main.CardType.CHANCE, "Chance Card", 23)
    fs = main.Card(main.CardType.PROPERTY, "Fleet Street", 24, b=220, c=main.Set.RED)
    ts = main.Card(main.CardType.PROPERTY, "Trafalgar Square", 25, b=240, c=main.Set.RED)
    fss = main.Card(main.CardType.RAILROAD, "Fenchurch St. Station", 26)
    ls = main.Card(main.CardType.PROPERTY, "Leicester Square", 27, b=260, c=main.Set.YELLOW)
    cos = main.Card(main.CardType.PROPERTY, "Coventry Street", 28, b=260, c=main.Set.YELLOW)
    water = main.Card(main.CardType.UTILITY, "Water Works", 29)
    picady = main.Card(main.CardType.PROPERTY, "Piccadilly", 30, b=280, c=main.Set.YELLOW)
    gotojail = main.Card(main.CardType.GOTOJAIL, "GO TO JAIL", 31)
    rgs = main.Card(main.CardType.PROPERTY, "Regent Street", 32, b=300, c=main.Set.GREEN)
    oxst = main.Card(main.CardType.PROPERTY, "Oxford Street", 33, b=300, c=main.Set.GREEN)
    community3 = main.Card(main.CardType.COMMUNITYCHEST, "Community Chest Card", 34)
    bos = main.Card(main.CardType.PROPERTY, "Bond Street", 35, b=320, c=main.Set.GREEN)
    lsst = main.Card(main.CardType.RAILROAD, "Liverpool St. Station", 36)
    chance3 = main.Card(main.CardType.CHANCE, "Chance Card", 37)
    pkln = main.Card(main.CardType.PROPERTY, "Park Lane", 38, b=350, c=main.Set.BLUE)
    suptx = main.Card(main.CardType.TAX, "Luxury Tax", 39, b=100)
    mayfr = main.Card(main.CardType.PROPERTY, "Mayfair", 40, b=400, c=main.Set.BLUE)

    board = [go, okr, chest1, wchr, itax, kcs, tai, chance1, er, pvr, jail, pm, ecomp, wh, nta, mbs, bs, chest2, gms, vs, fp, str, chance2, fs, ts, fss, ls, cos, water, picady, gotojail, rgs, oxst, community3, bos, lsst, chance3, pkln, suptx, mayfr]